apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: springboot
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: springboot
    name: springboot
  spec:
    host: springboot-development-saberkan.127.0.0.1.nip.io
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: springboot
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: springboot
    name: springboot
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: springboot
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 3
    labels:
      app: springboot
    name: springboot
  spec:
    replicas: 1
    selector:
      app: springboot
      deploymentconfig: springboot
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: springboot
          deploymentconfig: springboot
      spec:
        containers:
        - env:
          - name: application_name
            valueFrom:
              configMapKeyRef:
                key: application_name
                name: springboot-cm
          - name: environment
            valueFrom:
              configMapKeyRef:
                key: environment
                name: springboot-cm
          - name: port
            valueFrom:
              configMapKeyRef:
                key: port
                name: springboot-cm
          - name: version
            valueFrom:
              configMapKeyRef:
                key: version
                name: springboot-cm
          image: 172.30.1.1:5000/openshift/springboot@sha256:b14e38ae16949d18036073ccd129d56cd6365813f5ceeeadb1219b6605ac4e81
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 38
          name: springboot
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - springboot
        from:
          kind: ImageStreamTag
          name: springboot:latest
          namespace: openshift
        lastTriggeredImage: 172.30.1.1:5000/openshift/springboot@sha256:b14e38ae16949d18036073ccd129d56cd6365813f5ceeeadb1219b6605ac4e81
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: springboot
    name: springboot
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        namespace: openshift
        name: springboot:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: springboot-project/springboot
      git:
        ref: develop
        uri: https://github.com/saberkan/openshift-springboot-pipeline.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-maven-java:latest
          namespace: openshift
      type: Source
    triggers: []
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2019-01-31T23:55:03Z
    creationTimestamp: null
    generation: 1
    name: s2i-maven-java
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/openshift/s2i-maven-java:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    name: springboot
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/openshift/springboot:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
