kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "springboot-saberkan-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: >-
        def gitUrl =
        'https://github.com/saberkan/openshift-springboot-pipeline.git'


        node('maven') {
            stage ('Clone resources') {
                git url: gitUrl, branch: "develop"
            }
            stage ('Test application') {
                sh "cd springboot-project/springboot && mvn clean test"
            }
            stage ('buildInDevelopment') {
                openshiftBuild(namespace: 'development-saberkan', buildConfig: 'springboot', showBuildLogs: 'true')
            }
            stage ('promoteToStaging') {
                def userInput = input(
                    id: 'userInput', message: 'please provide version to promote to staging',
                    parameters: [
                            string(defaultValue: 'None',
                                    description: 'verison',
                                    name: 'version')
                    ])
                def version = userInput.version?:''
                
                openshiftTag(namespace: 'openshift', sourceStream: 'springboot',  sourceTag: 'latest', destinationStream: 'springboot', destinationTag: version)
                openshiftDeploy(namespace: 'staging-saberkan', deploymentConfig: 'springboot', )
            }
            openshiftScale(namespace: 'staging-saberkan', deploymentConfig: 'springboot',replicaCount: '2')
        }
    type: JenkinsPipeline
